name: Pronto

on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git fetch origin main
    - name: Pronto Run
      uses: ./
      with:
        target: origin/main
        runners: >-
          rubocop brakeman
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
